version: 2.1

references:
  set_environment_variables: &set_environment_variables
    run:
      name: Set Environment Variables
      command: |
        echo 'export CI_SHA1=$CIRCLE_SHA1' >> ${BASH_ENV}
        echo 'export CI_BRANCH=$CIRCLE_BRANCH' >> ${BASH_ENV}
        echo 'export CI_BUILD_NUM=$CIRCLE_BUILD_NUM' >> ${BASH_ENV}
        echo 'export CI_TAG=$CIRCLE_TAG' >> ${BASH_ENV}
        #        echo 'export ROK8S_INSTALL_PATH=${HOME}' >> ${BASH_ENV}
        #echo 'export ROK8S_DOCKER_BUILD_EXTRAARGS="--build-arg TRAVIS_BUILD_NUMBER=${CI_TAG:-${CI_SHA1}}"' >> ${BASH_ENV}

jobs:
  imagebuild:
    docker:
      - image: quay.io/reactiveops/ci-images:v11.3-alpine
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker
      - *set_environment_variables
      - run:
          name: Warm Docker cache
          command: |
            cp configurable-hpa/LICENSE.txt .
            docker-pull -f ${ROK8S_CONFIG}
      - run:
          name: Docker build
          command: |
            docker-build -f ${ROK8S_CONFIG}
      - run:
          name: Docker login
          command: docker login -u="reactiveops+circleci" -p="${quay_token}" quay.io
      - run:
          name: Docker push
          command: "docker-push -f ${ROK8S_CONFIG}"
    environment:
      ROK8S_CONFIG: quay.config

workflows:
  version: 2
  build_default:
    jobs:
    - imagebuild:
        context: org-global
        filters:
          tags:
            only: /\d+\.\d+\.\d+$/

